local controller = require("../Controllers/user")

return function(app)
    app.route({method = "POST", path = "/user"}, function(req, res)
        res.body, res.code, res.headers["Content-Type"] = controller.create(req.body)
    end)
    .route({method = "GET", path = "/user/:id"}, function(req, res)
        res.body, res.code, res.headers["Content-Type"] = controller.read_by_id(tonumber(req.params.id))
    end)
    .route({method = "GET", path = "/users"}, function(req, res)
        res.body, res.code, res.headers["Content-Type"] = controller.read_all()
    end)
    .route({method = "PATCH", path= "/user/:id"}, function(req, res)
        res.body, res.code, res.headers["Content-Type"] = controller.update_by_id(tonumber(req.params.id), req.body)
    end)
    .route({method = "DELETE", path = "/user/:id"}, function(req, res)
        res.body, res.code, res.headers["Content-Type"] = controller.delete(tonumber(req.params.id))
    end)
end